blog/urls.py
from django.urls import path

from .views import posts_of_following_profiles, posts_of_my_profiles, posts_of_all_profiles
app_name = "posts"

urlpatterns = [
    path('', posts_of_my_profiles, name='home'),
    path('all/', posts_of_all_profiles, name='all_posts'),
    path('sub/', posts_of_following_profiles, name='sub_posts'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    following = models.ManyToManyField(User, related_name='following', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def profiles_posts(self):
        return self.post_set.all()

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ('-created',)


class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.body)[:30]

    class Meta:
        ordering = ('-created',)

blog/views.py
from django.shortcuts import render
from .models import Post, Profile


def follow_unfollow(my_id, id_to_follow):
    profile = my_id
    pk = id_to_follow
    obj = Profile.objects.get(pk=pk)

    if obj.user in profile.following.all():
        print("remove :", "\n", obj.user, "\n", profile.following.all())
        profile.following.remove(obj.user)
    else:
        print("add :", "\n", obj.user, "\n", profile.following.all())
        profile.following.add(obj.user)
    return


def posts_of_following_profiles(request):
    profile = Profile.objects.get(user=request.user)

    users = [user for user in profile.following.all()]
    posts = []

    for u in users:
        p = Profile.objects.get(user=u)
        p_posts = p.post_set.all()
        posts.append(p_posts)

    my_posts = profile.profiles_posts()
    posts.append(my_posts)

    """ This command for adding User to follow/unfollow 
    (it should be turned on only once and turned off immediately after first page refresh) """
    # follow_unfollow(profile, 2)

    return render(request, 'home.html', {"profile": profile, "posts": posts})


def posts_of_my_profiles(request):
    profile = Profile.objects.get(user=request.user)
    posts = profile.profiles_posts()

    return render(request, 'home_all.html', {"profile": profile, "posts": posts})


def posts_of_all_profiles(request):
    posts = Post.objects.all()

    return render(request, 'home_all.html', {"posts": posts})

templates/base.html
<!-- templates/base.html -->
<html>
    <head>
        <title>Slava blog</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="">Slava blog</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'posts:all_posts' %}">All</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'posts:home' %}">User</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'posts:sub_posts' %}">Subscribed</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <div class="container-fluid">
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in posts %}
                {% for el in post %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{el.author}}</h2>
                            <p>{{el}}</p>
                            <p>Current User: {{profile}}</p>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>

    </div>
</div>
{% endblock content %}

templates/home_all.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in posts %}
                    <div class="card mb-4">
                        <div class="card-body">
                            <h2 class="card-title">{{post.author}}</h2>
                            <p>{{post.body}}</p>
                        </div>
                    </div>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock content %}